# Generated by Django 3.0.2 on 2020-02-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_status',
            field=models.CharField(choices=[('pr', 'Private'), ('pb', 'Published')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
