# Generated by Django 3.0.2 on 2020-02-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_entry_entry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='verified_adm',
            field=models.CharField(choices=[('ok', 'Verified'), ('no', 'Reject')], default='', max_length=2),
        ),
    ]
