# Generated by Django 3.0.2 on 2020-02-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_entry_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_status',
            field=models.CharField(choices=[('pr', 'Private'), ('pb', 'Published')], default='', max_length=2),
        ),
    ]
