# Generated by Django 3.0.2 on 2020-03-01 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0007_auto_20200301_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verificate',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='learning_logs.Entry')),
            ],
            bases=('learning_logs.entry',),
        ),
    ]
