# Generated by Django 3.0.2 on 2020-03-01 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0008_verificate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Verificate',
            new_name='ForVerification',
        ),
    ]
