# Generated by Django 3.0.2 on 2020-03-01 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0009_auto_20200301_1705'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForVerification',
        ),
    ]
